services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=psqlpassword
    env_file:
      - .env
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=psqlpassword
    depends_on:
      - db