databases:
  - name: bloggerdb
    plan: free
    databaseName: blogger
    user: blogger

services:
  - type: web
    plan: free
    name: blogger
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn blogger.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bloggerdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4