name: "Heartbeat"
on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping:
    runs-on: debian-10
    steps:
      - uses: actions/checkout@v3
      - run: .github/scripts/ping.sh